'use client';

import {
  SpaceDashboard,
  GridView,
  Settings,
  Build,
  People,
  Badge,
  Public,
  Star,
  LiveTv,
  CardGiftcard,
  Campaign,
  AccountBalance,
  Feedback,
  Article,
  Sms,
  Extension,
  Update,
  LocalAtm,
  SwapHoriz,
  Rule,
  AdminPanelSettings,
  History,
  Person,
  Mic,
  PhoneAndroid,
  Block,
  VpnKey,
  AttachMoney,
  Receipt,
  Movie,
  RssFeed,
  Help,
  VideoLibrary,
  QueueMusic,
  Timer,
  MusicNote,
  Storefront,
  Videocam,
  VideoCall,
  RecordVoiceOver,
  Visibility,
  Warning,
  VideoFile,
  Replay,
  Send,
  SportsEsports,
  Wallpaper,
  Schedule,
  Tag,
  Description,
  SmartToy,
  BarChart,
  Assignment,
  EmojiPeople,
  Chat,
  Groups,
  ListAlt,
  HowToReg,
  Category,
  DirectionsCar,
  Shield,
  CropOriginal,
  WorkspacePremium,
  EmojiEvents,
  EventNote,
  Flag,
  Notifications,
  Mail,
} from '@mui/icons-material';
import type { NavItem } from './types';

export const navConfig: NavItem[] = [
  { label: 'Dashboard', path: '/dashboard', icon: <SpaceDashboard /> },
  {
    label: 'System Management',
    icon: <GridView />,
    children: [
      {
        label: 'System Settings',
        icon: <Settings />,
        children: [
          { label: 'Advertising Configuration', path: '/dashboard/system/advertising', icon: <Campaign /> },
          { label: 'Exchange Rules', path: '/dashboard/system/exchange-rules', icon: <SwapHoriz /> },
          { label: 'Purchase rule list', path: '/dashboard/system/purchase-rules', icon: <Rule /> },
        ],
      },
      {
        label: 'Mobile platform settings',
        icon: <Build />,
        children: [
          { label: 'Mobile Configuration', path: '/dashboard/system/mobile-config', icon: <PhoneAndroid /> },
          { label: 'Nickname Restriction Configuration', path: '/dashboard/system/nickname-restriction', icon: <Block /> },
          { label: 'Encryption key configuration', path: '/dashboard/system/encryption-key', icon: <VpnKey /> },
        ],
      },
      { label: 'Administrator Management', path: '/dashboard/system/administrators', icon: <AdminPanelSettings /> },
      { label: 'Role Management', path: '/dashboard/system/roles', icon: <Badge /> },
      { label: 'Detailed System Operation Logs', path: '/dashboard/system/logs', icon: <History /> },
      { label: 'Country', path: '/dashboard/system/country', icon: <Public /> },
      { label: 'Popular countries', path: '/dashboard/system/popular-countries', icon: <Star /> },
    ],
  },
  {
    label: 'User Management',
    icon: <People />,
    children: [
      {
        label: 'User Management',
        icon: <Person />,
        children: [
          { label: 'User Management', path: '/dashboard/users', icon: <Person /> },
          { label: 'Robot avatar', path: '/dashboard/users/robot-avatar', icon: <SmartToy /> },
          { label: 'Private message gift statistics', path: '/dashboard/users/private-message-gifts', icon: <CardGiftcard /> },
          { label: 'Anchor Tags', path: '/dashboard/users/anchor-tags', icon: <Badge /> },
          { label: 'Income and expenditure records', path: '/dashboard/users/income-expenditure', icon: <AttachMoney /> },
          { label: 'Revenue records', path: '/dashboard/users/revenue', icon: <Receipt /> },
          { label: 'Blackout records', path: '/dashboard/users/blackout', icon: <Block /> }
        ],
      },
      { label: 'System Message Management', path: '/dashboard/users/system-messages', icon: <Sms /> },
      {
        label: 'Certification Management',
        icon: <HowToReg />,
        children: [
          { label: 'Anchor certification list', path: '/dashboard/users/certification/anchor', icon: <Mic /> },
          { label: 'Verified Name List', path: '/dashboard/users/certification/verified-names', icon: <Person /> },
        ],
      },
      {
        label: 'Level Management',
        icon: <BarChart />,
        children: [
          { label: 'Female Levels', path: '/dashboard/users/levels/female', icon: <BarChart /> },
          { label: 'Male Levels', path: '/dashboard/users/levels/male', icon: <BarChart /> },
        ],
      },
      { label: 'Task Management', path: '/dashboard/users/tasks', icon: <Assignment /> },
      {
        label: 'Family Management',
        icon: <Groups />,
        children: [
          { label: 'Family List', path: '/dashboard/users/family/list', icon: <ListAlt /> },
          { label: 'Family review', path: '/dashboard/reviews/family', icon: <HowToReg /> },
          { label: 'Family Level List', path: '/dashboard/users/family/levels', icon: <BarChart /> },
        ],
      },
      { label: 'Invitation Management', path: '/dashboard/users/invitations', icon: <EmojiPeople /> },
      { label: 'Chat history', path: '/dashboard/users/chat-history', icon: <Chat /> },
    ],
  },
  {
    label: 'Live Management',
    icon: <LiveTv />,
    children: [
      { label: 'PK Time Rule Setting', path: '/dashboard/live/pk-time-rules', icon: <Timer /> },
      { label: 'Call Rate Setting', path: '/dashboard/live/call-rate', icon: <VideoCall /> },
      { label: 'Live Room Sound Effects', path: '/dashboard/live/sound-effects', icon: <MusicNote /> },
      { label: 'Category Management', path: '/dashboard/live/categories', icon: <Category /> },
      {
        label: 'Live Management',
        icon: <Videocam />,
        children: [
          { label: 'Live room list', path: '/dashboard/live/rooms', icon: <Videocam /> },
          { label: 'Voice room', path: '/dashboard/live/voice-rooms', icon: <RecordVoiceOver /> },
          { label: 'Monitoring', path: '/dashboard/live/monitoring', icon: <Visibility /> },
          { label: 'Warning Content List', path: '/dashboard/live/warnings', icon: <Warning /> },
          { label: 'Live Ending Video', path: '/dashboard/live/ending-video', icon: <VideoFile /> },
          { label: 'Replay List', path: '/dashboard/live/replays', icon: <Replay /> },
          { label: 'Push Message List', path: '/dashboard/live/push-messages', icon: <Send /> },
          { label: 'PK Records', path: '/dashboard/live/pk-records', icon: <SportsEsports /> },
          { label: 'Room background cover', path: '/dashboard/live/room-backgrounds', icon: <Wallpaper /> },
          { label: 'Live Video Duration Task', path: '/dashboard/live/duration-tasks', icon: <Schedule /> },
          { label: 'Live Video Duration Task Log', path: '/dashboard/live/duration-task-logs', icon: <Description /> },
        ],
      },
      {
        label: 'Red Envelope Manage',
        icon: <CardGiftcard />,
        children: [
          { label: 'Red envelope list', path: '/dashboard/live/red-envelope/list', icon: <ListAlt /> },
          { label: 'Red Envelope Config', path: '/dashboard/live/red-envelope/config', icon: <Settings /> },
        ],
      },
      { label: 'Music management', path: '/dashboard/live/music', icon: <QueueMusic /> },
    ],
  },
  {
    label: 'Prop management',
    icon: <CardGiftcard />,
    children: [
      {
        label: 'Gift Management',
        icon: <CardGiftcard />,
        children: [
          { label: 'Gift List', path: '/dashboard/gifts', icon: <CardGiftcard /> },
          { label: 'Lucky Gift Management', path: '/dashboard/gifts/lucky', icon: <CardGiftcard /> },
        ],
      },
      {
        label: 'Car Management',
        icon: <DirectionsCar />,
        children: [
          { label: 'Car List', path: '/dashboard/cars', icon: <DirectionsCar /> },
          { label: 'Price configuration', path: '/dashboard/cars/prices', icon: <DirectionsCar /> },
          { label: 'Purchase Record', path: '/dashboard/cars/purchase-record', icon: <DirectionsCar /> },
          { label: 'Gift Record', path: '/dashboard/cars/gift-record', icon: <DirectionsCar /> },
        ],
      },
      {
        label: 'Guardian Management',
        icon: <Shield />,
        children: [
          { label: 'Guardian Category', path: '/dashboard/guardian/categories', icon: <Shield /> },
          { label: 'Purchase price configuration', path: '/dashboard/guardian/price-configs', icon: <Shield /> },
          { label: 'Privilege List', path: '/dashboard/guardian/privileges', icon: <Shield /> },
          { label: 'Guardian Record', path: '/dashboard/guardian/records', icon: <Shield /> },
        ],
      },
      {
        label: 'head frame',
        icon: <CropOriginal />,
        children: [
          { label: 'head frame list', path: '/dashboard/head-frame/list', icon: <CropOriginal /> },
          { label: 'Consumption Records', path: '/dashboard/head-frame/consumption-records', icon: <CropOriginal /> },
          { label: 'Gift Record', path: '/dashboard/head-frame/gift-record', icon: <CropOriginal /> },
        ],
      },
      {
        label: 'VIP member',
        icon: <WorkspacePremium />,
        children: [
          { label: 'VIP Purchase Rules', path: '/dashboard/vip/purchase-rules', icon: <WorkspacePremium /> },
          { label: 'VIP consumption record', path: '/dashboard/vip/consumption-record', icon: <WorkspacePremium /> },
        ],
      },
      {
        label: 'Fancy Number Management',
        icon: <Tag />,
        children: [
          { label: 'Fancy Number Management', path: '/dashboard/fancy-numbers', icon: <Tag /> },
          { label: 'Beautiful Number Consumption Record', path: '/dashboard/fancy-numbers/consumption', icon: <Receipt /> },
        ],
      },
      {
        label: 'Noble Management',
        icon: <EmojiEvents />,
        children: [
          { label: 'Noble Types', path: '/dashboard/noble/types', icon: <EmojiEvents /> },
          { label: 'Noble Privileges', path: '/dashboard/noble/privileges', icon: <Badge /> },
          { label: 'Noble Privilege', path: '/dashboard/noble/privilege', icon: <Star /> },
          { label: 'Noble recharge', path: '/dashboard/noble/recharge', icon: <EmojiEvents /> },
          { label: 'Noble recharge records', path: '/dashboard/noble/recharge-records', icon: <EmojiEvents /> },
          { label: 'Gift Record', path: '/dashboard/noble/gift-record', icon: <CardGiftcard /> },
        ],
      },
      {
        label: 'Check-in Management',
        icon: <EventNote />,
        children: [
          { label: 'Check-in Rewards', path: '/dashboard/check-in/rewards', icon: <EventNote /> },
          { label: 'Sign-in List', path: '/dashboard/check-in/sign-in-list', icon: <EventNote /> },
        ],
      },
      {
        label: 'Emoji management',
        icon: <EmojiPeople />,
        children: [
          { label: 'Emoji classification', path: '/dashboard/emoji/classification', icon: <Category /> },
          { label: 'Emoji List', path: '/dashboard/emoji/list', icon: <EmojiPeople /> },
        ],
      },
      { label: 'Store Items', path: '/dashboard/store', icon: <Storefront /> },
    ],
  },
  {
    label: 'Short Video Management',
    icon: <VideoLibrary />,
    children: [
      { label: 'Short Video List', path: '/dashboard/videos/list', icon: <Movie /> },
      { label: 'Short Video Comments', path: '/dashboard/videos/comments', icon: <Chat /> },
    ],
  },
  {
    label: 'Dynamic Management',
    icon: <Campaign />,
    children: [
      { label: 'Dynamic list', path: '/dashboard/dynamic/list', icon: <RssFeed /> },
      { label: 'Comment list', path: '/dashboard/dynamic/comments', icon: <Chat /> },
      { label: 'Dynamic Topics', path: '/dashboard/dynamic/topics', icon: <Tag /> },
    ],
  },
  {
    label: 'Fund Management',
    icon: <AccountBalance />,
    children: [
      { label: 'Payment interface', path: '/dashboard/fund/payment-interface', icon: <AccountBalance /> },
      { label: 'Recharge management', path: '/dashboard/fund/recharge', icon: <Receipt /> },
      { label: 'Bank List', path: '/dashboard/fund/bank-list', icon: <AccountBalance /> },
      {
        label: 'Withdrawal management',
        icon: <AccountBalance />,
        children: [
          { label: 'Withdrawal List', path: '/dashboard/fund/withdrawal/list', icon: <Receipt /> },
          { label: 'Family Withdrawal List', path: '/dashboard/fund/withdrawal/family', icon: <Receipt /> },
          { label: 'Withdrawal Pending Review Record', path: '/dashboard/fund/withdrawal/pending-review', icon: <Receipt /> },
          { label: 'Withdrawal Pending Confirmation Records', path: '/dashboard/fund/withdrawal/pending-confirmation', icon: <Receipt /> },
          { label: 'Invite user withdrawal list', path: '/dashboard/fund/withdrawal/invite-user', icon: <Receipt /> },
        ],
      },
      {
        label: 'Statistical management',
        icon: <BarChart />,
        children: [
          { label: 'Statistical charts', path: '/dashboard/fund/statistical/charts', icon: <BarChart /> },
          { label: 'Recharge Statistics', path: '/dashboard/fund/statistical/recharge', icon: <BarChart /> },
          { label: 'Withdrawal statistics', path: '/dashboard/fund/statistical/withdrawal', icon: <BarChart /> },
          { label: 'Anchor Daily Report', path: '/dashboard/fund/statistical/anchor-daily', icon: <BarChart /> },
          { label: 'monthly reporting form', path: '/dashboard/fund/statistical/monthly', icon: <BarChart /> },
        ],
      },
      { label: 'Manual recharge', path: '/dashboard/fund/manual-recharge', icon: <LocalAtm /> },
    ],
  },
  {
    label: 'Feedback Management',
    icon: <Feedback />,
    children: [
      {
        label: 'Report Management',
        icon: <Flag />,
        children: [
          { label: 'Report Type List', path: '/dashboard/reports/types', icon: <Flag /> },
          { label: 'Report List', path: '/dashboard/reports/list', icon: <Flag /> },
        ],
      },
    ],
  },
  {
    label: 'Article Management',
    icon: <Article />,
    children: [
      { label: 'Category Management List', path: '/dashboard/article/categories', icon: <Category /> },
      { label: 'Category Management Recycle Bin', path: '/dashboard/article/categories/recycle', icon: <Category /> },
      { label: 'Article Management List', path: '/dashboard/article/list', icon: <Article /> },
      { label: 'Article Management Recycle Bin', path: '/dashboard/article/recycle', icon: <Article /> },
      { label: 'Frequently Asked Questions', path: '/dashboard/help', icon: <Help /> },
    ],
  },
  {
    label: 'SMS Management',
    icon: <Sms />,
    children: [
      { label: 'SMS Interface List', path: '/dashboard/sms/interfaces', icon: <Send /> },
      { label: 'System Message List', path: '/dashboard/sms/messages', icon: <Notifications /> },
      { label: 'Business queue list', path: '/dashboard/sms/business-queue', icon: <Mail /> },
    ],
  },
  {
    label: 'Plugin management',
    icon: <Extension />,
    children: [
      { label: 'Plugin Configuration', path: '/dashboard/plugins', icon: <Extension /> },
      {
        label: 'Third party games',
        icon: <SportsEsports />,
        children: [
          { label: 'Game Configuration', path: '/dashboard/games/config', icon: <SportsEsports /> },
          { label: 'Game Records', path: '/dashboard/games/records', icon: <SportsEsports /> },
          { label: 'Game coin record', path: '/dashboard/games/coin-record', icon: <SportsEsports /> },
        ],
      },
    ],
  },
  {
    label: 'Version Management',
    icon: <Update />,
    children: [{ label: 'Version List', path: '/dashboard/versions', icon: <ListAlt /> }],
  },
  {
    label: 'Agent Recharge Management',
    icon: <LocalAtm />,
    children: [
      { label: 'Agent Account Management', path: '/dashboard/agent-recharge', icon: <ListAlt /> },
      { label: 'Bonus Receive', path: '/dashboard/agent-recharge/bonus-receive', icon: <CardGiftcard /> },
      { label: 'Receive Validation', path: '/dashboard/agent-recharge/receive-validation', icon: <HowToReg /> },
      { label: 'Recharge record', path: '/dashboard/agent-recharge/records', icon: <ListAlt /> },
      { label: 'Sales records', path: '/dashboard/agent-recharge/sales', icon: <ListAlt /> },
      { label: 'Invitation record', path: '/dashboard/agent-recharge/invitations', icon: <ListAlt /> },
    ],
  },
];
